### ISSUE TITLE
download()

### ISSUE THREAD

**Issue by stephenwilliams22** [chartgerink/osfr#22] opened 2017-01-31 20:35 UTC
When you only have read permission to a file it cannot be downloaded. Was this intentional? Users are given access to download on the osf if they have read permissions.

**Comment by chartgerink** [comment] 2017-02-03 06:31
This certainly was not the intention. I am able to download this public file.
```r
> osfr::download(id = '9zkux', public=TRUE)
Saving to filename: manuscript.pdf
Successfully downloaded file.
[1] "manuscript.pdf"
```

Can you share a bit more about the id you're trying to download? (note: only files can be downloaded at the moment)

**Comment by stephenwilliams22** [comment] 2017-02-03 06:37
I have access to a private file that I only have read permissions to. I can easily download it through my browser but when I try through R I get denied. I have no problem downloading public files through R.

**Comment by chartgerink** [comment] 2017-02-03 06:43
Hm okay. I will try to look into this over the weekend. Sorry for the inconvenience.

**Comment by stephenwilliams22** [comment] 2017-02-03 06:57
Not a problem. For example take this file https://osf.io/zwrxm/. I have read access but it is private. I get this error 'Error in download("zwrxm") : Failed. Sure you have access to the file?' Tim or Alex at COS can probably help you test if necessary. They are admins on this project.

**Comment by chartgerink** [comment] 2017-09-22 11:24
Sorry for taking ages to get back to this. I cannot reproduce your problem, are you sure you were logged in and specified that it was a private file?

Note: `download()` changed to `download_file()` upon PR #23

**Comment by chartgerink** [comment] 2017-11-07 09:14
Closing this issue due to non-activity and lack of reproducing. Will reopen if @stephenwilliams22 problem persists.

**Closed by chartgerink** 2017-11-07 09:14 UTC
